### ISSUE TITLE
Licensing information ? 

### ISSUE THREAD

**Issue by d0p1s4m4** [Damdoshi/LibLapin#13]
Consider adding a LICENSE file ~~and choosing a license (if not already) because for now we have no information about that~~ because it's hard to know if we don't pay attention to 'debian/' folder

**Comment by Damdoshi** [comment]
Ok. I'll add one.



True, and considering the debian directory is currently quite useless... it is even more true.

**Comment by d0p1s4m4** [comment]
fixed by #18
