### ISSUE TITLE
SAMPLE_PER_SECONDS isn't defined

### ISSUE THREAD

**Issue by GMoxFr** [Damdoshi/LibLapin#20]
SAMPLE_PER_SECOND have been removed form include/lapin/sound.h in commit 5fbb11bc83d42c1a625a1306f7da25ce39916312. So I'm not able to use bunny_new_effect anymore.

<img width="1550" alt="Capture d’écran 2021-06-09 à 11 11 49" src="https://user-images.githubusercontent.com/18314221/121327185-818d1300-c913-11eb-9cd3-5f2f3cf7deef.png">

**Comment by Damdoshi** [comment]
Thank you. = ) 
Fixed by 97a1c93b26476f9abdce7ef62b14b37c034c0d9a
