### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [Damdoshi/LibLapin#7]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [bpt::NetCom::Server::RawRead](https://github.com/Damdoshi/LibLapin/blob/989744545382f590a8e26787bb6a425204436aef/src/deps/srv/ReadOnNetwork.cpp#L10 "bpt::NetCom::Server::RawRead function")
- [SmallConf::Clear](https://github.com/Damdoshi/LibLapin/blob/152b763e5666f7416b23bd12e1be9e67d8888cf1/src/configuration/smallconf/Clear.cpp#L9 "SmallConf::Clear function")

**Comment by Damdoshi** [comment]
Thank you.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/Damdoshi/LibLapin/commit/828e53a934b254ec05736a456ed53d4ef86617d4 "Deletion of a few unnecessary checks").
